daemon off;

worker_processes 1;

error_log stderr notice;

events {
    worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    server_name localhost;
    server_tokens off;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://api.example.com/;
        proxy_http_version 1.1;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|svg)$ {
        expires modified +24h;
        access_log off;
        etag on;
        add_header Cache-Control "public";
    }

    location ~* \.(?:css|js)$ {
        expires modified +24h;
        access_log off;
        etag on;
        add_header Cache-Control "public";
    }
  }
}

